#!/usr/bin/python3
import sys
import collections

all_timezones = []

for line in sys.stdin:
    args = line.split(" ")
    timezone = args[5].split("\n")[0]
    all_timezones.append(timezone)

counts = collections.Counter(all_timezones)

index_arr = []

for key in counts:
    index_arr.append((int(key), key))

index_arr.sort()

for tup in index_arr:
    key = tup[1]
    print(key + " " + str(counts[key]))#!/bin/bash

